# Generated by Django 5.0.1 on 2024-02-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('requirements', models.TextField()),
                ('app_deadline', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
